name: Terraform Apply

permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch:

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    needs: []
    environment: dev
    name: Terraform Apply

    steps:
      - name: Clone Repository (Latest)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform apply successfully
        shell: bash
        run: |
          terraform init
          terraform apply --auto-approve -input=false -var='use_msi=false' -var='subscription_id=${{ secrets.SUBSCRIPTION_ID}}'

      - name: Terraform apply failed
        shell: bash
        run: |
          terraform init
          terraform apply --auto-approve -input=false -var='use_msi=true' -var='subscription_id=${{ secrets.SUBSCRIPTION_ID}}'
